targets:
  $default:
    sources:
      include:
        - lib/**
        - web/**
        - test/**
        - $package$
    builders:
      build_web_compilers|entrypoint:
        generate_for:
          include:
            - "test/unit/**.dart.browser_test.dart"
            - "web/**.dart"
        release_options:
          dart2js_args:
            - --no-minify
            - -O3
      

# Hack-y solution for source maps pending more permanent solution:
# https://github.com/dart-lang/build/issues/1779
global_options:
  build_web_compilers|dart_source_cleanup:
    release_options:
      enabled: false
  build_web_compilers|dart2js_archive_extractor:
    release_options:
      filter_outputs: false
